name: Lint and Format Swift Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Install Homebrew and tools
      - name: Install Homebrew, SwiftLint & SwiftFormat
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'export PATH="/opt/homebrew/bin:$PATH"' >> $GITHUB_ENV
          export PATH="/opt/homebrew/bin:$PATH"
          brew install swiftlint swiftformat

      # Remove trailing whitespace automatically
      - name: Remove trailing whitespace
        run: swiftformat . --trim-whitespace

      # Run SwiftLint
      - name: Run SwiftLint
        run: swiftlint
